export type SpaceShot = {
  id: string
  src: string
  name: string
  traits: { label: string; value: string }[]
}

export const SPACE_SHOTS: SpaceShot[] = [
  {
    id: '0041',
    src: '/space/nest-astronaut.png',
    name: 'NIDUS#0041',
    traits: [
      { label: 'subject', value: 'Astronaut' },
      { label: 'background', value: 'Butter' },
      { label: 'suit', value: 'White-coral' },
      { label: 'mood', value: 'Wave' },
      { label: 'signal', value: 'Keep-alpha' },
    ],
  },
  {
    id: '0112',
    src: '/space/nest-ship.png',
    name: 'NIDUS#0112',
    traits: [
      { label: 'subject', value: 'Spaceship' },
      { label: 'background', value: 'Mint' },
      { label: 'thrust', value: 'Magenta' },
      { label: 'hull', value: 'Teal-orange' },
      { label: 'signal', value: 'Keep-beta' },
    ],
  },
  {
    id: '0208',
    src: '/space/nest-asteroid.png',
    name: 'NIDUS#0208',
    traits: [
      { label: 'subject', value: 'Asteroid' },
      { label: 'background', value: 'Sky' },
      { label: 'surface', value: 'Orange-lavender' },
      { label: 'glow', value: 'Warm' },
      { label: 'signal', value: 'Keep-rock' },
    ],
  },
  {
    id: '0330',
    src: '/space/nest-alien.png',
    name: 'NIDUS#0330',
    traits: [
      { label: 'subject', value: 'Alien' },
      { label: 'background', value: 'Peach' },
      { label: 'coat', value: 'Lime' },
      { label: 'eyes', value: 'Wide' },
      { label: 'signal', value: 'Keep-xeno' },
    ],
  },
  {
    id: '0444',
    src: '/space/nest-planet.png',
    name: 'NIDUS#0444',
    traits: [
      { label: 'subject', value: 'Planet' },
      { label: 'background', value: 'Lilac' },
      { label: 'rings', value: 'Magenta' },
      { label: 'face', value: 'Smile' },
      { label: 'signal', value: 'Keep-core' },
    ],
  },
  {
    id: '0517',
    src: '/space/nest-mars.png',
    name: 'NIDUS#0517',
    traits: [
      { label: 'subject', value: 'Surface' },
      { label: 'background', value: 'Cream' },
      { label: 'ground', value: 'Lava-craters' },
      { label: 'tone', value: 'Rust' },
      { label: 'signal', value: 'Keep-land' },
    ],
  },
  {
    id: '0622',
    src: '/space/nest-ufo.png',
    name: 'NIDUS#0622',
    traits: [
      { label: 'subject', value: 'UFO' },
      { label: 'background', value: 'Coral' },
      { label: 'lights', value: 'Rainbow' },
      { label: 'beam', value: 'Cyan' },
      { label: 'signal', value: 'Keep-saucer' },
    ],
  },
  {
    id: '0701',
    src: '/space/nest-satellite.png',
    name: 'NIDUS#0701',
    traits: [
      { label: 'subject', value: 'Satellite' },
      { label: 'background', value: 'Blush' },
      { label: 'panels', value: 'Blue' },
      { label: 'body', value: 'Yellow' },
      { label: 'signal', value: 'Keep-link' },
    ],
  },
  {
    id: '0814',
    src: '/space/nest-alien-b.png',
    name: 'NIDUS#0814',
    traits: [
      { label: 'subject', value: 'Alien' },
      { label: 'background', value: 'Lemon' },
      { label: 'coat', value: 'Teal' },
      { label: 'spots', value: 'Orange' },
      { label: 'signal', value: 'Keep-xeno-b' },
    ],
  },
  {
    id: '0920',
    src: '/space/nest-rocket.png',
    name: 'NIDUS#0920',
    traits: [
      { label: 'subject', value: 'Rocket' },
      { label: 'background', value: 'Aqua' },
      { label: 'flame', value: 'Orange' },
      { label: 'hull', value: 'Retro' },
      { label: 'signal', value: 'Keep-boost' },
    ],
  },
  {
    id: '1033',
    src: '/space/nest-astronaut-b.png',
    name: 'NIDUS#1033',
    traits: [
      { label: 'subject', value: 'Astronaut' },
      { label: 'background', value: 'Lavender' },
      { label: 'suit', value: 'Cyan-pink' },
      { label: 'mood', value: 'Rest' },
      { label: 'signal', value: 'Keep-ground' },
    ],
  },
  {
    id: '1148',
    src: '/space/nest-comet.png',
    name: 'NIDUS#1148',
    traits: [
      { label: 'subject', value: 'Comet' },
      { label: 'background', value: 'Teal' },
      { label: 'tail', value: 'Fire-pink' },
      { label: 'core', value: 'Bright' },
      { label: 'signal', value: 'Keep-streak' },
    ],
  },
  {
    id: '1205',
    src: '/space/cartoon-spaceship.png',
    name: 'NIDUS#1205',
    traits: [
      { label: 'subject', value: 'Cruiser' },
      { label: 'field', value: 'Void' },
      { label: 'planet', value: 'Ringed-pink' },
      { label: 'thrust', value: 'Neon' },
      { label: 'signal', value: 'Keep-void-run' },
    ],
  },
  {
    id: '1311',
    src: '/space/cartoon-astronaut.png',
    name: 'NIDUS#1311',
    traits: [
      { label: 'subject', value: 'Walker' },
      { label: 'field', value: 'Void' },
      { label: 'suit', value: 'White' },
      { label: 'tether', value: 'Pink' },
      { label: 'signal', value: 'Keep-drift' },
    ],
  },
  {
    id: '1426',
    src: '/space/cartoon-planet.png',
    name: 'NIDUS#1426',
    traits: [
      { label: 'subject', value: 'Orb' },
      { label: 'field', value: 'Void' },
      { label: 'rings', value: 'Thin' },
      { label: 'tone', value: 'Magenta' },
      { label: 'signal', value: 'Keep-orbit' },
    ],
  },
  {
    id: '1502',
    src: '/space/cartoon-ufo.png',
    name: 'NIDUS#1502',
    traits: [
      { label: 'subject', value: 'Disc' },
      { label: 'field', value: 'Void' },
      { label: 'beam', value: 'Soft' },
      { label: 'hull', value: 'Chrome' },
      { label: 'signal', value: 'Keep-hover' },
    ],
  },
  {
    id: '1639',
    src: '/space/cartoon-alien.png',
    name: 'NIDUS#1639',
    traits: [
      { label: 'subject', value: 'Visitor' },
      { label: 'field', value: 'Void' },
      { label: 'coat', value: 'Green' },
      { label: 'eyes', value: 'Oval' },
      { label: 'signal', value: 'Keep-hello' },
    ],
  },
  {
    id: '1744',
    src: '/space/cartoon-rocket.png',
    name: 'NIDUS#1744',
    traits: [
      { label: 'subject', value: 'Booster' },
      { label: 'field', value: 'Void' },
      { label: 'flame', value: 'Amber' },
      { label: 'fins', value: 'Red' },
      { label: 'signal', value: 'Keep-lift' },
    ],
  },
  {
    id: '1850',
    src: '/space/galaxy-1.jpg',
    name: 'NIDUS#1850',
    traits: [
      { label: 'subject', value: 'Earthrise' },
      { label: 'field', value: 'Orbit' },
      { label: 'clouds', value: 'Swirl' },
      { label: 'tone', value: 'Blue' },
      { label: 'signal', value: 'Keep-home' },
    ],
  },
  {
    id: '1918',
    src: '/space/nebula-1.jpg',
    name: 'NIDUS#1918',
    traits: [
      { label: 'subject', value: 'Nebula' },
      { label: 'field', value: 'Deep' },
      { label: 'gas', value: 'Rose-violet' },
      { label: 'dust', value: 'Thick' },
      { label: 'signal', value: 'Keep-cloud' },
    ],
  },
  {
    id: '2027',
    src: '/space/moon-1.jpg',
    name: 'NIDUS#2027',
    traits: [
      { label: 'subject', value: 'Moon' },
      { label: 'field', value: 'Close' },
      { label: 'craters', value: 'Dense' },
      { label: 'tone', value: 'Silver' },
      { label: 'signal', value: 'Keep-luna' },
    ],
  },
  {
    id: '2140',
    src: '/space/planet-1.jpg',
    name: 'NIDUS#2140',
    traits: [
      { label: 'subject', value: 'World' },
      { label: 'field', value: 'Far' },
      { label: 'bands', value: 'Storm' },
      { label: 'tone', value: 'Amber' },
      { label: 'signal', value: 'Keep-giant' },
    ],
  },
  {
    id: '2255',
    src: '/space/spaceship-1.png',
    name: 'NIDUS#2255',
    traits: [
      { label: 'subject', value: 'Freighter' },
      { label: 'field', value: 'Transit' },
      { label: 'hull', value: 'Matte' },
      { label: 'lights', value: 'Cabin' },
      { label: 'signal', value: 'Keep-haul' },
    ],
  },
  {
    id: '2309',
    src: '/space/astronaut-1.jpg',
    name: 'NIDUS#2309',
    traits: [
      { label: 'subject', value: 'EVA' },
      { label: 'field', value: 'Station' },
      { label: 'visor', value: 'Reflect' },
      { label: 'suit', value: 'White' },
      { label: 'signal', value: 'Keep-walk' },
    ],
  },
  {
    id: '2804',
    src: '/space/galaxy-2.jpg',
    name: 'NIDUS#2804',
    traits: [
      { label: 'subject', value: 'Spiral' },
      { label: 'field', value: 'Deep' },
      { label: 'arms', value: 'Dust' },
      { label: 'core', value: 'Bright' },
      { label: 'signal', value: 'Keep-spin' },
    ],
  },
  {
    id: '2912',
    src: '/space/nebula-2.jpg',
    name: 'NIDUS#2912',
    traits: [
      { label: 'subject', value: 'Bloom' },
      { label: 'field', value: 'Deep' },
      { label: 'gas', value: 'Cyan-pink' },
      { label: 'stars', value: 'Dense' },
      { label: 'signal', value: 'Keep-bloom' },
    ],
  },
  {
    id: '3020',
    src: '/space/asteroid-2.png',
    name: 'NIDUS#3020',
    traits: [
      { label: 'subject', value: 'Shard' },
      { label: 'field', value: 'Belt' },
      { label: 'surface', value: 'Pitted' },
      { label: 'tone', value: 'Iron' },
      { label: 'signal', value: 'Keep-shard' },
    ],
  },
  {
    id: '3144',
    src: '/space/spaceship-2.png',
    name: 'NIDUS#3144',
    traits: [
      { label: 'subject', value: 'Scout' },
      { label: 'field', value: 'Transit' },
      { label: 'hull', value: 'Sleek' },
      { label: 'thrust', value: 'Blue' },
      { label: 'signal', value: 'Keep-scout' },
    ],
  },
  {
    id: '3251',
    src: '/space/planet-2.jpg',
    name: 'NIDUS#3251',
    traits: [
      { label: 'subject', value: 'Sphere' },
      { label: 'field', value: 'Far' },
      { label: 'atmosphere', value: 'Haze' },
      { label: 'tone', value: 'Rust-blue' },
      { label: 'signal', value: 'Keep-sphere' },
    ],
  },
  {
    id: '3360',
    src: '/space/alien-1.png',
    name: 'NIDUS#3360',
    traits: [
      { label: 'subject', value: 'Contact' },
      { label: 'field', value: 'Close' },
      { label: 'coat', value: 'Odd' },
      { label: 'eyes', value: 'Bright' },
      { label: 'signal', value: 'Keep-meet' },
    ],
  },
  {
    id: '3472',
    src: '/space/stars-1.jpg',
    name: 'NIDUS#3472',
    traits: [
      { label: 'subject', value: 'Field' },
      { label: 'field', value: 'Deep' },
      { label: 'stars', value: 'Dense' },
      { label: 'tone', value: 'Cold' },
      { label: 'signal', value: 'Keep-night' },
    ],
  },
]

/** Same objects by reference, reordered — rails must not look identical. */
export const SPACE_SHOTS_B: SpaceShot[] = [
  SPACE_SHOTS[18],
  SPACE_SHOTS[6],
  SPACE_SHOTS[24],
  SPACE_SHOTS[12],
  SPACE_SHOTS[2],
  SPACE_SHOTS[27],
  SPACE_SHOTS[9],
  SPACE_SHOTS[20],
  SPACE_SHOTS[0],
  SPACE_SHOTS[15],
  SPACE_SHOTS[25],
  SPACE_SHOTS[4],
  SPACE_SHOTS[13],
  SPACE_SHOTS[1],
  SPACE_SHOTS[21],
  SPACE_SHOTS[8],
  SPACE_SHOTS[14],
  SPACE_SHOTS[3],
  SPACE_SHOTS[19],
  SPACE_SHOTS[10],
  SPACE_SHOTS[28],
  SPACE_SHOTS[7],
  SPACE_SHOTS[16],
  SPACE_SHOTS[22],
  SPACE_SHOTS[5],
  SPACE_SHOTS[11],
  SPACE_SHOTS[23],
  SPACE_SHOTS[17],
  SPACE_SHOTS[26],
  SPACE_SHOTS[29],
]

/** Rails 3 and 4 — only rendered at 960px and below. */
export const SPACE_SHOTS_C: SpaceShot[] = [
  SPACE_SHOTS[11],
  SPACE_SHOTS[22],
  SPACE_SHOTS[5],
  SPACE_SHOTS[17],
  SPACE_SHOTS[28],
  SPACE_SHOTS[3],
  SPACE_SHOTS[14],
  SPACE_SHOTS[26],
  SPACE_SHOTS[7],
  SPACE_SHOTS[19],
  SPACE_SHOTS[1],
  SPACE_SHOTS[12],
  SPACE_SHOTS[23],
  SPACE_SHOTS[9],
  SPACE_SHOTS[0],
  SPACE_SHOTS[16],
  SPACE_SHOTS[27],
  SPACE_SHOTS[8],
  SPACE_SHOTS[21],
  SPACE_SHOTS[4],
  SPACE_SHOTS[15],
  SPACE_SHOTS[29],
  SPACE_SHOTS[10],
  SPACE_SHOTS[2],
  SPACE_SHOTS[18],
  SPACE_SHOTS[6],
  SPACE_SHOTS[25],
  SPACE_SHOTS[13],
  SPACE_SHOTS[20],
  SPACE_SHOTS[24],
]

export const SPACE_SHOTS_D: SpaceShot[] = [
  SPACE_SHOTS[25],
  SPACE_SHOTS[8],
  SPACE_SHOTS[16],
  SPACE_SHOTS[29],
  SPACE_SHOTS[4],
  SPACE_SHOTS[13],
  SPACE_SHOTS[21],
  SPACE_SHOTS[1],
  SPACE_SHOTS[10],
  SPACE_SHOTS[19],
  SPACE_SHOTS[27],
  SPACE_SHOTS[6],
  SPACE_SHOTS[14],
  SPACE_SHOTS[22],
  SPACE_SHOTS[3],
  SPACE_SHOTS[11],
  SPACE_SHOTS[18],
  SPACE_SHOTS[26],
  SPACE_SHOTS[7],
  SPACE_SHOTS[15],
  SPACE_SHOTS[23],
  SPACE_SHOTS[0],
  SPACE_SHOTS[9],
  SPACE_SHOTS[17],
  SPACE_SHOTS[28],
  SPACE_SHOTS[5],
  SPACE_SHOTS[12],
  SPACE_SHOTS[20],
  SPACE_SHOTS[2],
  SPACE_SHOTS[24],
]
